### ISSUE TITLE
Consider implementing untagged decryption mode for select use cases

### ISSUE THREAD

**Issue by Intensity** [jedisct1/rust-rocca#2]
Although Rocca is an authenticated encryption mode producing and consuming a tag, it's possible that the user may deliberately not want to validate with a tag in some cases (they may not have it, or they may be achieving integrity checking in another way). I may point to a kind of "daisy chained" series of AEAD operations, or a length-preserving all-or-nothing-transform as examples.

And so this is a suggestion to consider a variant in this (and related/Morus) code to not validate against a tag when the user deliberately wants to do that.

A related idea is to have the decrypt _produce_ the tag that the in-place encryption would have produced, and to return it instead of consuming it.

**Comment by jedisct1** [comment]
The Rocca update function could be used to build a stream cipher. But that's really not Rocca any more.

That would also be a very dangerous API. Not something good to have in a general-purpose library.
